# Generated by Django 5.1.7 on 2025-04-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos",
                to="scheduling.flight",
            ),
        ),
    ]
