# Generated by Django 5.1.7 on 2025-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_flight_status_alter_cargo_flight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="allocated",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="flight",
        ),
        migrations.AddField(
            model_name="cargo",
            name="cargo_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargo",
            name="destination",
            field=models.CharField(default="Mumbai", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cargo",
            name="weight",
            field=models.FloatField(),
        ),
    ]
