# Generated by Django 5.1.7 on 2025-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_remove_cargo_allocated_remove_cargo_flight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="destination",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
