# Generated by Django 5.1.7 on 2025-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_alter_cargo_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="allocated",
            field=models.BooleanField(default=False),
        ),
    ]
