# Generated by Django 5.1.7 on 2025-04-02 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_cargo_allocated"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargo",
            name="departure_city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="cargo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="allocated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="cargo_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="destination",
            field=models.CharField(db_index=True, default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="weight",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.1)]
            ),
        ),
    ]
