# Generated by Django 5.1.7 on 2025-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_cargo_created_at_cargo_departure_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="original_arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Delayed", "Delayed"),
                    ("On Time", "On Time"),
                    ("Taken Off", "Taken Off"),
                    ("Landed", "Landed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
