# Generated by Django 5.1.7 on 2025-04-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_cargo_priority_flight_base_cost_per_km"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="original_arrival_time",
        ),
    ]
